spring:
  cloud:
    stream:
      bindings:
        output:
          destination: transformed
        test-sink:
          destination: transformed
        input:
          destination: testtock
        test-source:
          destination: testtock

        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json