server:
  port: 30100

spring:
  application:
    name: generator-visit

  cloud:
    stream:
      bindings:
        visits:
          destination: visits
#          contentType: application/json

generator:
  weights:
    doctors: [0.1, 0.1, 0.1, 0.1, 0.1]
    clinics: [0.1, 0.2, 0.5, 0.1, 0.1]
    patients: [0.1, 0.2, 0.5, 0.1, 0.1]
