server:
  port: 8081

spring:
  application:
    name: generator-visit

  cloud:
    stream:
      bindings:

        visits-out:
          destination: visits
          contentType: application/json

        input:
          destination: visits