spring:
  cloud:
    stream:
      bindings:

        visits-out:
          destination: visits
          contentType: application/json

        input:
          destination: visits

        output:
          destination: visits-processed

        visits-in:
          destination: visits-processed
          contentType: application/json