spring:
  cloud:
    stream:
      bindings:
        visits-in:
          destination: visits
          contentType: application/json
        visits-out:
          destination: visits
          contentType: application/json